# 应用配置
kafka:
  bootstrapServers: cdh03:6667,cdh04:6667,cdh05:6667
  topic: ods-gb-all
  groupId: data-quality-group
  autoOffsetReset: latest

process:
  parallelism: 1
  stateRetentionMinutes: 60
  checkpointInterval: 60000

# Doris规则库配置
dorisRule:
  url: jdbc:mysql://10.2.96.62:9030/battery_quality?useSSL=false&serverTimezone=Asia/Shanghai
  username: adi_bigdata
  password: adi_bigdata@2025
  database: battery_quality
  maxPoolSize: 10
  minPoolSize: 2
  connectionTimeout: 30000
  cacheRefreshInterval: 30

# Sink配置
sink:
  # 选择使用的Sink类型: doris, print
  type: doris

# Doris配置
doris:
  conn: 10.2.96.62:8030
  user: adi_bigdata
  passwd: adi_bigdata@2025
  database: battery_quality
  table: ods_data_with_issues
  batchSize: 5000
  batchIntervalMs: 30000
  maxRetries: 2147483647
  maxBatchBytes: 1073741824

# 打印Sink配置
print:
  # 打印输出的标识符
  identifier: "质量检查结果"
  # 是否打印详细信息
  verbose: true